# Generated by Django 3.2 on 2021-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_orderamount_productamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=1000, help_text='in US dollars'),
            preserve_default=False,
        ),
    ]
