# Generated by Django 3.2 on 2021-05-03 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
